# Generated by Django 3.1.3 on 2021-03-06 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ko', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=300)),
                ('poster', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TopMovie',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ko', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=300)),
                ('poster', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorldCup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField()),
                ('championCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField()),
                ('rating', models.FloatField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('bestMovie', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
